import {useEffect,useRef,useState} from "react";
import katex from "katex";
import "katex/dist/katex.min.css";
import "./styles.css";
type R={p:string;n:string;i:string};
const routes:R[]=[
{p:"/dashboard",n:"Dashboard",i:"▦"},{p:"/upload",n:"Upload & Analyze",i:"↑"},{p:"/processing",n:"AI Processing",i:"✦"},
{p:"/library",n:"Library",i:"▤"},{p:"/document",n:"Document Detail",i:"▱"},{p:"/questions",n:"Questions Explorer",i:"?"},
{p:"/question",n:"Question Detail",i:"✓"},{p:"/review",n:"Review Center",i:"◈"},{p:"/chapters",n:"Chapters & Topics",i:"≡"},
{p:"/practice",n:"Practice",i:"▶"},{p:"/practice/session",n:"Practice Session",i:"◷"},{p:"/practice/results",n:"Practice Results",i:"↗"},
{p:"/analytics",n:"Analytics",i:"⌁"},{p:"/search",n:"Search",i:"⌕"},{p:"/settings",n:"Settings",i:"⚙"},{p:"/first-run",n:"First Run",i:"✦"}];
const go=(p:string)=>{history.pushState({},'',p);dispatchEvent(new PopStateEvent('popstate'))};
function Side({path,close}:{path:string;close:()=>void}){return <aside className="side"><div className="brand"><b>M</b><span><strong>ModuleIQ</strong><small>Knowledge workspace</small></span></div><div className="workspace">● &nbsp;Personal workspace　⌄</div><nav>{routes.slice(0,14).map(r=><button className={path===r.p?'nav active':'nav'} onClick={()=>{go(r.p);close()}} key={r.p}><i>{r.i}</i>{r.n}</button>)}</nav><div className="side-bottom"><button className={path==='/settings'?'nav active':'nav'} onClick={()=>{go('/settings');close()}}>⚙ Settings</button><div className="profile"><b>S</b><span>My workspace<small>Local-first</small></span></div></div></aside>}
function Header({title,menu}:{title:string;menu:()=>void}){return <header><button className="hamb" onClick={menu}>☰</button><div><small>Workspace /</small><b>{title}</b></div><div className="top"><button onClick={()=>go('/search')} className="search">⌕ <span>Search knowledge...</span><kbd>⌘ K</kbd></button><button>?</button><b className="avatar">S</b></div></header>}
function Btn({children,primary=false,onClick}:{children:React.ReactNode;primary?:boolean;onClick?:()=>void}){return <button onClick={onClick} className={primary?'btn primary':'btn'}>{children}</button>}
function Card({children,cl="",onClick}:{children:React.ReactNode;cl?:string;onClick?:()=>void}){return <section className={"card "+cl} onClick={onClick}>{children}</section>}
const materials=["Physics — Mechanics","Organic Chemistry Notes","Linear Algebra Workbook"];
const questions=["Newton's laws in a moving frame","Calculate the limiting reagent","Eigenvalues of a 3×3 matrix","Projectile motion with air resistance"];
function Dashboard(){return <Page t="Dashboard"><div className="hero"><Card cl="hero-card"><span className="tag purple">KNOWLEDGE WORKSPACE</span><h1>Turn your material into <em>knowledge.</em></h1><p>Upload notes, textbooks and question papers. ModuleIQ structures them into searchable, practice-ready knowledge.</p><Btn primary onClick={()=>go('/upload')}>＋ Add material</Btn> <Btn onClick={()=>go('/library')}>Open library</Btn><div className="orb">✦</div></Card><Card cl="health"><small>Knowledge health</small><strong>84%</strong><div className="bar"><i style={{width:'84%'}}/></div><div className="mini"><span><b>42</b>Topics</span><span><b>186</b>Questions</span><span><b>23</b>Reviews</span></div></Card></div><Title t="Continue learning" s="Pick up where you left off."/><div className="grid3"><Card><span className="tag purple">MECHANICS</span><h3>Newton's Laws</h3><p>12 concepts · 68% mastery</p><div className="bar"><i style={{width:'68%'}}/></div></Card><Card><span className="tag green">READY</span><h3>3 reviews due</h3><p>Low-confidence concepts and repeated mistakes.</p><Btn onClick={()=>go('/review')}>Review now</Btn></Card><Card><span className="tag">AI STATUS</span><h3>Provider connected</h3><p>Your knowledge persists independently of AI.</p><Btn onClick={()=>go('/settings')}>Manage</Btn></Card></div><Title t="Recent materials" s="Your knowledge base at a glance."/><Table rows={materials}/></Page>}
function Table({rows}:{rows:string[]}){return <Card cl="table"><div className="thead">Material　　Format　　 Structure　　 Updated</div>{rows.map((x,i)=><div className="trow" onClick={()=>go('/document')} key={x}><b>▱　{x}</b><span>PDF</span><span>{i+9} chapters</span><small>{i?'Yesterday':'2h ago'}</small>›</div>)}</Card>}
function Upload(){const [busy,setBusy]=useState(false);const [error,setError]=useState("");const inputRef=useRef<HTMLInputElement>(null);const submit=async(files:FileList|null)=>{if(!files?.length)return;setBusy(true);setError("");try{for(const file of Array.from(files)){const form=new FormData();form.append("file",file);const res=await fetch((import.meta.env.VITE_API_BASE_URL||"http://127.0.0.1:8000/api")+"/ingestion/upload",{method:"POST",body:form});const data=await res.json();if(!res.ok)throw new Error(data.detail||"Upload failed");if(data.processing_job_id){go("/processing?job="+data.processing_job_id);return}}}catch(e){setError(e instanceof Error?e.message:"Upload failed")}finally{setBusy(false)}};return <Page t="Upload & Analyze"><Card cl="drop"><input ref={inputRef} type="file" accept="application/pdf,.pdf" multiple hidden onChange={e=>submit(e.target.files)}/><div className="upload">↑</div><span className="tag purple">BYOM</span><h1>Bring your material</h1><p>Drop PDFs, notes, worksheets or question papers here.</p><Btn primary onClick={()=>inputRef.current?.click()}>{busy?"Uploading...":"Choose files"}</Btn><small>PDF up to 250 MB · Multiple files supported</small>{error&&<p className="upload-error">{error}</p>}</Card><div className="grid3"><Info t="Secure validation" d="Integrity, format, metadata and duplicate checks."/><Info t="Multiple sources" d="Keep several documents inside one living knowledge base."/><Info t="AI-assisted structure" d="AI enriches extracted objects; the database stays canonical."/></div></Page>}

function Info({t,d}:{t:string;d:string}){return <Card><span className="iconbox">✦</span><h3>{t}</h3><p>{d}</p></Card>}
function Processing(){const [job,setJob]=useState<any>(null);useEffect(()=>{const id=new URLSearchParams(location.search).get("job");if(!id)return;let active=true;const poll=async()=>{try{const res=await fetch((import.meta.env.VITE_API_BASE_URL||"http://127.0.0.1:8000/api")+"/ingestion/jobs/"+id);if(res.ok&&active)setJob(await res.json())}catch{}if(active)setTimeout(poll,1200)};poll();return()=>{active=false}},[]);const stages=job?.stages||[["validation","pending"],["document_analysis","pending"],["extraction","pending"],["normalization","pending"],["finalization","pending"]];return <Page t="AI Processing"><Card><span className="tag purple">PROCESSING</span><h2>Material ingestion</h2><p>{job?"Tracking real processing job "+job.id:"Waiting for an uploaded material."}</p><strong className="percent">{job?.status||"queued"}</strong><div className="bar big"><i style={{width:(job?Math.max(8,Math.round(stages.reduce((n:any,s:any)=>n+(s.progress||0),0)/stages.length*100)):8)+"%"}}/></div>{stages.map((s:any,i:number)=>{const name=s.name||s[0];const status=s.status||s[1];return <div className="stage" key={name}><b>{status==="complete"?"✓":i+1}</b><span>{name.replaceAll("_"," ")}<small>{status}</small></span><strong>{Math.round((s.progress||0)*100)}%</strong></div>})}</Card><Card><Title t="Extraction snapshot" s="Structured objects appear here as the document engine runs."/><div className="four">{[['—','Pages'],['—','Blocks'],['—','Equations'],['—','Tables']].map(x=><div><b>{x[0]}</b><small>{x[1]}</small></div>)}</div></Card></Page>}

function Library(){return <Page t="Library"><Title t="Your materials" s="Everything that feeds your knowledge base." a={<Btn primary onClick={()=>go('/upload')}>＋ Add material</Btn>}/><div className="filters"><input placeholder="⌕ Filter materials..."/><span className="tag purple">All</span><span className="tag">PDF</span><span className="tag">Recent</span></div><div className="grid3">{materials.map((x,i)=><Card cl="material" key={x} onClick={()=>go('/document')}><div className={'cover c'+i}><span>MODULEIQ</span><b>{x.split(' ')[0]}</b></div><span className="tag">PDF</span><h3>{x}</h3><p>{i+9} chapters · recently updated</p><footer>● Structured <b>›</b></footer></Card>)}</div></Page>}
function Document(){return <Page t="Document Detail"><Card cl="doc"><div className="cover c0"><span>MODULEIQ</span><b>PHYSICS</b></div><div><span className="tag green">PROCESSED</span><h1>Physics — Mechanics</h1><p>142 pages · 14 chapters · Imported Oct 2, 2026</p><Btn primary onClick={()=>go('/chapters')}>Explore knowledge</Btn> <Btn onClick={()=>go('/questions')}>Questions</Btn></div></Card><div className="four">{[['142','Pages'],['1,284','Blocks'],['37','Equations'],['18','Tables']].map(x=><Card><b>{x[0]}</b><small>{x[1]}</small></Card>)}</div><Title t="Structure" s="What ModuleIQ understood."/><div className="grid3"><Info t="14 Chapters" d="Mechanics → Kinematics → Dynamics → Work & Energy..." /><Info t="186 Questions" d="Classified, deduplicated and linked to source pages."/><Info t="92% Confidence" d="Low-confidence objects route to Review Center."/></div></Page>}
function Questions(){return <Page t="Questions Explorer"><Title t="Question bank" s="186 structured questions across your materials." a={<Btn primary onClick={()=>go('/practice')}>Start practice</Btn>}/><div className="filters"><input placeholder="⌕ Search questions..."/><span className="tag purple">All topics</span><span className="tag">Difficulty</span><span className="tag">Type</span></div><Table rows={questions}/></Page>}
function MathText({text}:{text:string}){const html=text.replace(/\$([^$]+)\$/g,(_,m)=>katex.renderToString(m,{throwOnError:false}));return <span dangerouslySetInnerHTML={{__html:html}}/>}
function SolutionsPanel(){
const [data,setData]=useState<any>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState("");
const id=new URLSearchParams(location.search).get("id");
useEffect(()=>{if(!id)return;fetch((import.meta.env.VITE_API_BASE_URL||"http://127.0.0.1:8000/api")+"/solutions/question/"+id).then(r=>r.ok?r.json():Promise.reject()).then(setData).catch(()=>setError("Unable to load solutions."))},[id]);
const generate=async()=>{const provider=prompt("Provider ID for AI solution");if(!provider||!id)return;setBusy(true);setError("");try{const r=await fetch((import.meta.env.VITE_API_BASE_URL||"http://127.0.0.1:8000/api")+"/solutions/generate/"+id+"?provider_id="+encodeURIComponent(provider),{method:"POST"});const body=await r.json();if(!r.ok)throw new Error(body.detail||"Generation failed");setData({question_id:id,solutions:[{type:"source",body:body.source_solution.body,confidence:1},{type:"ai",body:body.ai_solution.answer,confidence:body.ai_solution.confidence,metadata:{steps:body.ai_solution.steps,verification:body.ai_solution.verification,related_objects:body.ai_solution.related_objects}}]})}catch(e){setError(e instanceof Error?e.message:"Generation failed")}finally{setBusy(false)}};
return <Card cl="solutions"><Title t="Solutions" s="Original source answers remain distinct from AI-generated explanations." a={<Btn primary onClick={generate}>{busy?"Generating...":"Generate AI solution"}</Btn>}/>{error&&<p>{error}</p>}{!id&&<p>Open this screen with ?id=&lt;question-id&gt; to inspect a persisted question.</p>}{data?.solutions?.map((s:any)=><div className="solution" key={s.id||s.type}><span className={s.type==="source"?"tag green":"tag purple"}>{s.type==="source"?"ORIGINAL SOURCE":"AI EXPLANATION"}</span><div className="solution-body"><MathText text={s.body||""}/></div>{s.metadata?.steps?.map((step:string,i:number)=><p key={i}><b>Step {i+1}.</b> <MathText text={step}/></p>)}<small>Confidence: {Math.round((s.confidence||0)*100)}%</small></div>)}</Card>}
}
function Question(){return <Page t="Question Detail"><div className="two"><Card><span className="tag purple">MECHANICS</span> <span className="tag">MEDIUM</span><p>Source p.42</p><h1>A body moves with constant acceleration. How does its velocity change with time?</h1><div className="options">{["It remains constant","It changes linearly","It changes exponentially","It becomes zero"].map((x,i)=><button className={i===1?"option selected":"option"} key={x}><b>{String.fromCharCode(65+i)}</b>{x}</button>)}</div><Btn primary>Submit answer</Btn> <Btn onClick={()=>go("/review")}>Flag for review</Btn></Card><Card><span className="tag green">92% CONFIDENCE</span><h3>Source & provenance</h3><p>Physics — Mechanics · Page 42 · Block 17</p><hr/><h3>Classification</h3><p>Mechanics / Kinematics / Constant acceleration</p></Card></div><SolutionsPanel/></Page>}
function Review(){return <Page t="Review Center"><Title t="Needs your attention" s="Uncertain or problematic knowledge that benefits from human review."/><div className="review">{[['Classification','Newton’s third law','Low confidence · 61%'],['Question','Projectile motion diagram','Ambiguous extraction · p.78'],['Solution','Conservation of momentum','AI verification pending'],['Repeated mistake','Free-body diagrams','Missed 3 times']].map(x=><Card><span className="tag purple">{x[0]}</span><h3>{x[1]}</h3><p>{x[2]}</p><Btn>Inspect →</Btn></Card>)}</div></Page>}
function Chapters(){return <Page t="Chapters & Topics"><div className="two"><Card><Title t="Physics — Mechanics" s="14 chapters · 42 topics · 96 concepts"/>{['Vectors & Motion','Kinematics','Newton’s Laws','Work & Energy','Momentum','Circular Motion'].map((x,i)=><button className="chapter"><b>0{i+1}</b><span>{x}<small>{i+4} topics</small></span>›</button>)}</Card><Card><span className="tag purple">SELECTED TOPIC</span><h2>Kinematics</h2><p>Motion described through position, velocity and acceleration.</p><div className="tree">● Position<br/>● Displacement<br/>● Velocity<br/>● Acceleration<br/>　↳ Constant acceleration</div><Btn primary onClick={()=>go('/practice')}>Practice topic</Btn></Card></div></Page>}
function Practice(){return <Page t="Practice"><Title t="Choose your session" s="Practice adapts to your actual learner state."/><div className="practice">{[['Fast Mode','Quick targeted practice','10 questions'],['Deep Practice','Build understanding with explanations','20 questions'],['Boss Session','Challenge across weak areas','30 questions'],['Custom','Choose topics, difficulty and type','Your settings']].map((x,i)=><Card onClick={()=>go('/practice/session')}><span className="practice-icon">✦</span><span className="tag purple">{i?'MODE':'RECOMMENDED'}</span><h2>{x[0]}</h2><p>{x[1]}</p><b>{x[2]}</b><strong>→</strong></Card>)}</div></Page>}
function Session(){const [s,setS]=useState('');return <Page t="Practice Session"><div className="sessionbar"><span><span className="tag purple">FAST MODE</span><h2>Kinematics</h2></span><b>4 / 10</b><span className="timer">◷ 08:42</span></div><Card><small>QUESTION 04 · MEDIUM</small><h1>A particle starts from rest and accelerates uniformly at 2 m/s². What is its velocity after 5 seconds?</h1><div className="options">{['5 m/s','10 m/s','12 m/s','20 m/s'].map(x=><button onClick={()=>setS(x)} className={s===x?'option selected':'option'}><b>{x[0]}</b>{x}</button>)}</div><Btn onClick={()=>go('/practice/results')}>Skip</Btn> <Btn primary onClick={()=>go('/practice/results')}>Submit answer</Btn></Card></Page>}
function Results(){return <Page t="Practice Results"><Card cl="result"><div className="score">82<small>/100</small></div><div><span className="tag green">SESSION COMPLETE</span><h1>Good session.</h1><p>10 questions · 8 correct · 2 missed · 11m 24s</p><Btn primary onClick={()=>go('/practice')}>Practice again</Btn></div></Card><div className="four">{[['8','Correct'],['2','Needs review'],['11m','Time'],['82%','Score']].map(x=><Card><b>{x[0]}</b><small>{x[1]}</small></Card>)}</div><Title t="What to work on" s="These signals feed your learner model."/><div className="grid3"><Info t="Free-body diagrams" d="Weakness · 2 mistakes across 3 attempts."/><Info t="Vector decomposition" d="Prerequisite · review before the next set."/><Info t="Constant acceleration" d="Improving · +14% mastery this week."/></div></Page>}
function Analytics(){return <Page t="Analytics"><Title t="Learning analytics" s="Your actual practice behavior, not decorative metrics."/><div className="four">{[['84%','Overall mastery'],['+12%','This month'],['186','Questions'],['23','Topics active']].map(x=><Card><b>{x[0]}</b><small>{x[1]}</small></Card>)}</div><div className="two"><Card><h3>Mastery trend</h3><div className="chart">{[32,45,41,58,64,72,84].map(h=><i style={{height:h+'%'}}/>)}</div></Card><Card><h3>Weak topics</h3>{['Free-body diagrams','Rotational dynamics','Vector decomposition','Energy conservation'].map((x,i)=><div className="weak"><span>{x}</span><b>{61+i*6}%</b></div>)}</Card></div></Page>}
function Search(){return <Page t="Search"><Card cl="searchcard"><input autoFocus placeholder="Search documents, topics, questions, equations..."/><p><span className="tag purple">momentum</span> <span className="tag">equation of motion</span> <span className="tag">questions I missed</span></p></Card><Title t="Recent results" s="Search spans your structured knowledge."/><div className="grid3">{[['Concept','Conservation of momentum'],['Question','Impulse and collision'],['Equation','p = mv']].map(x=><Card><span className="tag purple">{x[0]}</span><h3>{x[1]}</h3><p>Physics — Mechanics · source-linked</p></Card>)}</div></Page>}
function Settings(){return <Page t="Settings"><div className="settings"><Card><Title t="AI provider" s="Bring your own key. Your knowledge remains yours."/><div className="provider"><b>G</b><span><strong>Google Gemini</strong><small>Connected · Gemini 2.5 Flash</small></span><span className="tag green">ACTIVE</span><Btn>Change</Btn></div><div className="key"><span>API key</span><code>••••••••••••••••</code><Btn>Replace</Btn><Btn>Delete</Btn></div></Card><Card><h3>Workspace</h3><label>Workspace name<input defaultValue="Personal workspace"/></label><label>Default knowledge base<input defaultValue="My Knowledge"/></label><Btn primary>Save changes</Btn></Card><Card><h3>Data portability</h3><p>Export structured knowledge, questions, analytics and documents.</p><Btn>Export data</Btn> <Btn>Import backup</Btn></Card></div></Page>}
function First(){return <Page t="First Run"><Card cl="first"><div className="orb">✦</div><span className="tag purple">WELCOME TO MODULEIQ</span><h1>Your material. Your knowledge.</h1><p>Start with your own material, connect an AI provider when you want intelligence, and build a knowledge workspace that persists independently.</p><div className="steps"><b>01 Add material</b><b>02 Connect AI</b><b>03 Start learning</b></div><Btn primary onClick={()=>go('/upload')}>Set up my workspace →</Btn></Card></Page>}
function Title({t,s,a}:{t:string;s?:string;a?:React.ReactNode}){return <div className="title"><div><h2>{t}</h2>{s&&<p>{s}</p>}</div>{a}</div>}
function Page({t,children}:{t:string;children:React.ReactNode}){return <div className="page"><Header title={t} menu={()=>dispatchEvent(new Event('mi-menu'))}/><main>{children}</main></div>}
function Screen({p}:{p:string}){if(p==='/upload')return <Upload/>;if(p==='/processing')return <Processing/>;if(p==='/library')return <Library/>;if(p==='/document')return <Document/>;if(p==='/questions')return <Questions/>;if(p==='/question')return <Question/>;if(p==='/review')return <Review/>;if(p==='/chapters')return <Chapters/>;if(p==='/practice')return <Practice/>;if(p==='/practice/session')return <Session/>;if(p==='/practice/results')return <Results/>;if(p==='/analytics')return <Analytics/>;if(p==='/search')return <Search/>;if(p==='/settings')return <Settings/>;if(p==='/first-run')return <First/>;return <Dashboard/>}
export function App(){const[path,setPath]=useState(location.pathname);const[open,setOpen]=useState(false);useEffect(()=>{const f=()=>setPath(location.pathname);const m=()=>setOpen(v=>!v);addEventListener('popstate',f);addEventListener('mi-menu',m);return()=>{removeEventListener('popstate',f);removeEventListener('mi-menu',m)}},[]);return <div className="app">{open&&<div className="scrim" onClick={()=>setOpen(false)}/>}<div className={open?'sidewrap open':'sidewrap'}><Side path={path} close={()=>setOpen(false)}/></div><Screen p={routes.some(r=>r.p===path)?path:'/dashboard'}/></div>}
